# coding: utf-8

"""
A sample API conforming to the OGC API - Processes - Part 1 standard

This document is an API definition document provided alongside the OGC API - Processes standard. The OGC API - Processes Standard specifies a processing interface to communicate over a RESTful protocol using JavaScript Object Notation (JSON) encodings. The specification allows for the wrapping of computational tasks into executable processes that can be offered by a server and be invoked by a client application.

The version of the OpenAPI document: 1.0.0
Contact: standards-team@ogc.org
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest


class TestTransmissionMode(unittest.TestCase):
    """TransmissionMode unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTransmissionMode(self):
        """Test TransmissionMode"""
        # inst = TransmissionMode()


if __name__ == "__main__":
    unittest.main()
