# coding: utf-8

"""
A sample API conforming to the OGC API - Processes - Part 1 standard

This document is an API definition document provided alongside the OGC API - Processes standard. The OGC API - Processes Standard specifies a processing interface to communicate over a RESTful protocol using JavaScript Object Notation (JSON) encodings. The specification allows for the wrapping of computational tasks into executable processes that can be offered by a server and be invoked by a client application.

The version of the OpenAPI document: 1.0.0
Contact: standards-team@ogc.org
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from ogc_api_processes_client.models.description_type_additional_parameters import (
    DescriptionTypeAdditionalParameters,
)


class TestDescriptionTypeAdditionalParameters(unittest.TestCase):
    """DescriptionTypeAdditionalParameters unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DescriptionTypeAdditionalParameters:
        """Test DescriptionTypeAdditionalParameters
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `DescriptionTypeAdditionalParameters`
        """
        model = DescriptionTypeAdditionalParameters()
        if include_optional:
            return DescriptionTypeAdditionalParameters(
                title = '',
                role = '',
                href = '',
                parameters = [
                    ogc_api_processes_client.models.additional_parameter.additionalParameter(
                        name = '', 
                        value = [
                            null
                            ], )
                    ]
            )
        else:
            return DescriptionTypeAdditionalParameters(
        )
        """

    def testDescriptionTypeAdditionalParameters(self):
        """Test DescriptionTypeAdditionalParameters"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
