# coding: utf-8

# flake8: noqa
"""
A sample API conforming to the OGC API - Processes - Part 1 standard

This document is an API definition document provided alongside the OGC API - Processes standard. The OGC API - Processes Standard specifies a processing interface to communicate over a RESTful protocol using JavaScript Object Notation (JSON) encodings. The specification allows for the wrapping of computational tasks into executable processes that can be offered by a server and be invoked by a client application.

The version of the OpenAPI document: 1.0.0
Contact: standards-team@ogc.org
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

# import models into model package
from ogc_api_processes_client.models.additional_parameter import AdditionalParameter
from ogc_api_processes_client.models.additional_parameter_value_inner import (
    AdditionalParameterValueInner,
)
from ogc_api_processes_client.models.bbox import Bbox
from ogc_api_processes_client.models.conf_classes import ConfClasses
from ogc_api_processes_client.models.description_type import DescriptionType
from ogc_api_processes_client.models.description_type_additional_parameters import (
    DescriptionTypeAdditionalParameters,
)
from ogc_api_processes_client.models.exception import Exception
from ogc_api_processes_client.models.execute import Execute
from ogc_api_processes_client.models.execute200_response import Execute200Response
from ogc_api_processes_client.models.execute_inputs_value import ExecuteInputsValue
from ogc_api_processes_client.models.format import Format
from ogc_api_processes_client.models.format_schema import FormatSchema
from ogc_api_processes_client.models.inline_or_ref_data import InlineOrRefData
from ogc_api_processes_client.models.input_description import InputDescription
from ogc_api_processes_client.models.input_description_all_of_max_occurs import (
    InputDescriptionAllOfMaxOccurs,
)
from ogc_api_processes_client.models.input_value import InputValue
from ogc_api_processes_client.models.input_value_no_object import InputValueNoObject
from ogc_api_processes_client.models.job_control_options import JobControlOptions
from ogc_api_processes_client.models.job_list import JobList
from ogc_api_processes_client.models.landing_page import LandingPage
from ogc_api_processes_client.models.link import Link
from ogc_api_processes_client.models.metadata import Metadata
from ogc_api_processes_client.models.model_schema import ModelSchema
from ogc_api_processes_client.models.output import Output
from ogc_api_processes_client.models.output_description import OutputDescription
from ogc_api_processes_client.models.process import Process
from ogc_api_processes_client.models.process_list import ProcessList
from ogc_api_processes_client.models.process_summary import ProcessSummary
from ogc_api_processes_client.models.qualified_input_value import QualifiedInputValue
from ogc_api_processes_client.models.reference import Reference
from ogc_api_processes_client.models.schema_one_of import SchemaOneOf
from ogc_api_processes_client.models.schema_one_of_additional_properties import (
    SchemaOneOfAdditionalProperties,
)
from ogc_api_processes_client.models.schema_one_of_not import SchemaOneOfNot
from ogc_api_processes_client.models.status_code import StatusCode
from ogc_api_processes_client.models.status_info import StatusInfo
from ogc_api_processes_client.models.subscriber import Subscriber
from ogc_api_processes_client.models.transmission_mode import TransmissionMode
