# coding: utf-8

"""
    A sample API conforming to the OGC API - Processes - Part 1 standard

    This document is an API definition document provided alongside the OGC API - Processes standard. The OGC API - Processes Standard specifies a processing interface to communicate over a RESTful protocol using JavaScript Object Notation (JSON) encodings. The specification allows for the wrapping of computational tasks into executable processes that can be offered by a server and be invoked by a client application.

    The version of the OpenAPI document: 1.0.0
    Contact: standards-team@ogc.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, ValidationError, field_validator
from typing import Any, Optional
from ogc_api_processes_client.models.input_value_no_object import InputValueNoObject
from ogc_api_processes_client.models.link import Link
from ogc_api_processes_client.models.qualified_input_value import QualifiedInputValue
from typing import Union, Set, Dict
from typing_extensions import Self

INLINEORREFDATA_ONE_OF_SCHEMAS = ["InputValueNoObject", "Link", "QualifiedInputValue"]

class InlineOrRefData(BaseModel):
    """
    InlineOrRefData
    """
    # data type: InputValueNoObject
    oneof_schema_1_validator: Optional[InputValueNoObject] = None
    # data type: QualifiedInputValue
    oneof_schema_2_validator: Optional[QualifiedInputValue] = None
    # data type: Link
    oneof_schema_3_validator: Optional[Link] = None
    actual_instance: Optional[Union[InputValueNoObject, Link, QualifiedInputValue]] = None
    one_of_schemas: Set[str] = { "InputValueNoObject", "Link", "QualifiedInputValue" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        error_messages = []
        match = 0
        # validate data type: InputValueNoObject
        if not isinstance(v, InputValueNoObject):
            error_messages.append(f"Error! Input type `{type(v)}` is not `InputValueNoObject`")
        else:
            match += 1
        # validate data type: QualifiedInputValue
        if not isinstance(v, QualifiedInputValue):
            error_messages.append(f"Error! Input type `{type(v)}` is not `QualifiedInputValue`")
        else:
            match += 1
        # validate data type: Link
        if not isinstance(v, Link):
            error_messages.append(f"Error! Input type `{type(v)}` is not `Link`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in InlineOrRefData with oneOf schemas: InputValueNoObject, Link, QualifiedInputValue. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in InlineOrRefData with oneOf schemas: InputValueNoObject, Link, QualifiedInputValue. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into InputValueNoObject
        try:
            instance.actual_instance = InputValueNoObject.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into QualifiedInputValue
        try:
            instance.actual_instance = QualifiedInputValue.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into Link
        try:
            instance.actual_instance = Link.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into InlineOrRefData with oneOf schemas: InputValueNoObject, Link, QualifiedInputValue. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into InlineOrRefData with oneOf schemas: InputValueNoObject, Link, QualifiedInputValue. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], InputValueNoObject, Link, QualifiedInputValue]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


