# coding: utf-8

"""
    A sample API conforming to the OGC API - Processes - Part 1 standard

    This document is an API definition document provided alongside the OGC API - Processes standard. The OGC API - Processes Standard specifies a processing interface to communicate over a RESTful protocol using JavaScript Object Notation (JSON) encodings. The specification allows for the wrapping of computational tasks into executable processes that can be offered by a server and be invoked by a client application.

    The version of the OpenAPI document: 1.0.0
    Contact: standards-team@ogc.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, ValidationError, field_validator
from typing import Any, Optional
from ogc_api_processes_client.models.reference import Reference
from typing import Union, Set, Dict
from typing_extensions import Self

MODELSCHEMA_ONE_OF_SCHEMAS = ["Reference", "SchemaOneOf"]

class ModelSchema(BaseModel):
    """
    ModelSchema
    """
    # data type: Reference
    oneof_schema_1_validator: Optional[Reference] = None
    # data type: SchemaOneOf
    oneof_schema_2_validator: Optional[SchemaOneOf] = None
    actual_instance: Optional[Union[Reference, SchemaOneOf]] = None
    one_of_schemas: Set[str] = { "Reference", "SchemaOneOf" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        error_messages = []
        match = 0
        # validate data type: Reference
        if not isinstance(v, Reference):
            error_messages.append(f"Error! Input type `{type(v)}` is not `Reference`")
        else:
            match += 1
        # validate data type: SchemaOneOf
        if not isinstance(v, SchemaOneOf):
            error_messages.append(f"Error! Input type `{type(v)}` is not `SchemaOneOf`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in ModelSchema with oneOf schemas: Reference, SchemaOneOf. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in ModelSchema with oneOf schemas: Reference, SchemaOneOf. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into Reference
        try:
            instance.actual_instance = Reference.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into SchemaOneOf
        try:
            instance.actual_instance = SchemaOneOf.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into ModelSchema with oneOf schemas: Reference, SchemaOneOf. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into ModelSchema with oneOf schemas: Reference, SchemaOneOf. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], Reference, SchemaOneOf]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())

from ogc_api_processes_client.models.schema_one_of import SchemaOneOf  # noqa: E402
# TODO: Rewrite to not use raise_errors
ModelSchema.model_rebuild(raise_errors=False)

