# coding: utf-8

"""
    A sample API conforming to the OGC API - Processes - Part 1 standard

    This document is an API definition document provided alongside the OGC API - Processes standard. The OGC API - Processes Standard specifies a processing interface to communicate over a RESTful protocol using JavaScript Object Notation (JSON) encodings. The specification allows for the wrapping of computational tasks into executable processes that can be offered by a server and be invoked by a client application.

    The version of the OpenAPI document: 1.0.0
    Contact: standards-team@ogc.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class TransmissionMode(str, Enum):
    """
    TransmissionMode
    """

    """
    allowed enum values
    """
    VALUE = 'value'
    REFERENCE = 'reference'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of TransmissionMode from a JSON string"""
        return cls(json.loads(json_str))


